# Generated by Django 4.2.7 on 2025-01-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=6, verbose_name='性別')),
            ],
        ),
        migrations.CreateModel(
            name='ThriftRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='商品名')),
                ('size', models.CharField(max_length=2, verbose_name='サイズ')),
                ('status', models.TextField(verbose_name='状態')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('image1', models.ImageField(upload_to='thrifts', verbose_name='イメージ１')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='thrifts', verbose_name='イメージ２')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='thrift.category', verbose_name='カテゴリ')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genders', to='thrift.gender', verbose_name='性別')),
            ],
        ),
    ]
